config/routes.rb
Rails.application.routes.draw do

  resources :shares do
    resources :comments
    resources :votes, only: [:show, :update, :create], shallow: true
  end

  resources :users, only: [:new, :create, :edit, :update, :show] do
    resources :shares, only: [:index], action: :user_shares
    resources :comments, only: [:index], action: :user_comments
    get '/edit/password', action: :edit_password, as: :edit_password
    patch '/password', action: :update_password, as: :update_password
  end

  root 'shares#index'
  resource :session, only: [:new, :create, :destroy]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :share
end

app/models/share.rb
class Share < ApplicationRecord
  belongs_to :user
  has_many :comments
  has_many :votes
  validates :title, presence: true, length: { maximum: 200 }

  def net_votes
    self.votes.reduce(0) { |sum, vote| sum + vote.value }
  end

end

app/models/user.rb
class User < ApplicationRecord
  has_many :shares
  has_many :comments
  has_many :votes
  validates :email, uniqueness: true

  def password=(unhashed_password)
    @_password = BCrypt::Password.create(unhashed_password)
    self.password_digest = @_password
  end

  def password
    @_password ||= BCrypt::Password.new(password_digest)
  end

end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :user
  belongs_to :share
  validates :value, numericality: { greater_than: -2, less_than: 2 }
  validates :user, uniqueness: { scope: :share, message: "User can only vote on a share once" }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user
  def current_user
     User.find_by(id: session["current_user_id"])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :logged_in?, only: [:new, :create]
  before_action :authorized?, only: [:destroy, :edit, :update]

  def logged_in?
    flash[:danger] = "You must be logged in to complete that action"
    redirect_to new_session_path unless current_user
  end

  def authorized?
    flash[:danger] = "You are not the owner of that item"
    redirect_to "/" unless current_user == Comment.find(params["id"]).user
  end

  def new
    if current_user
      @comment = Comment.new()
      @share = Share.find(params["share_id"])
      render :new
    else
      @message = "You must be logged in to comment"
      render new_session_path
    end
  end

  def create
    @share = Share.find(params["share_id"])
    @comment = @share.comments.build(comment_params)
    @comment.user = current_user
    if @comment.save
      redirect_to share_comments_path
    else
      render :new
    end
  end

  def edit
    @comment = Comment.find(params["id"])
    @share = @comment.share
  end

  def update
    @comment = Comment.find(params["id"])
    @share = @comment.share
    if @comment.update(comment_params)
      redirect_to share_comments_path
    else
      render :edit
    end
  end

  def index
    @share = Share.find(params["share_id"])
    @comments = @share.comments.reverse
  end

  def destroy
    Comment.find(params["id"]).destroy
    redirect_to share_comments_path
  end

  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    @user = User.find_by(email: params[:email])

    if @user && @user.password == params[:password]
      session["current_user_id"] = @user.id
      redirect_to shares_path
    else
      @message = "You username or password was not correct"
      render :new
    end
  end

  def destroy
    session.delete("current_user_id")
    redirect_to shares_path
  end
end

app/controllers/shares_controller.rb
class SharesController < ApplicationController
  before_action :logged_in?, only: [:new, :create]
  before_action :authorized?, only: [:destroy, :edit, :update]

  def logged_in?
    flash[:danger] = "You must be logged in to complete that action"
    redirect_to new_session_path unless current_user
  end

  def authorized?
    flash[:danger] = "You are not the owner of that item"
    redirect_to "/" unless current_user == Share.find(params["id"]).user
  end

  def new
    if current_user
      @share = Share.new()
      render :new
    else
      @message = "You must be logged in to create a post"
      @shares = Share.all.reverse
      render new_session_path
    end
  end

  def create
    @user = current_user
    @share = @user.shares.build(share_params)
    if @share.save
      redirect_to shares_path, flash: { success: "Share was successful" }
    else
      render :new
    end
  end

  def index
    @shares = Share.all.reverse
  end

  def destroy
    if current_user
      Share.find(params["id"]).destroy
      redirect_to shares_path
    else
      @message="You must log in to delete content"
    end
  end

  def edit
    @share = Share.find(params["id"])
  end

  def update
    @share = Share.find(params["id"])
    if @share.update(share_params) && @share.user == current_user
      redirect_to shares_path
    else
      @message = "You are not logged in as the owner of this post"
    end
  end

  def user_shares
    @user = User.find(params["user_id"])
    @shares = @user.shares.reverse
  end

  def share_params
    params.require(:share).permit(:title, :url)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new()
  end

  def create
    @user = User.new(user_params)
    if params[:user][:password] == ""
      @message = "Password can't be blank"
      render :new
    elsif @user.save
      session["message"] = "Thank you for signing up!"
      session["current_user_id"] = @user.id
      redirect_to shares_path
    else
      render :new
    end
  end

  def edit
    @user = User.find(params["id"])
  end

  def update
    @user = User.find(params["id"])
    if @user.update(user_params)
      render :show
    else
      render :edit
    end
  end

  def edit_password
    @user = User.find(params["user_id"])
  end

  def update_password
    @user = User.find(params["user_id"])
    if params[:user_password][:password] == params[:user_password][:confirm_password] && @user.update(user_password_params)
      redirect_to user_path(current_user.id)
    elsif params[:user_password][:password] != params[:user_password][:confirm_password]
      @message = "Passwords don't match!"
      render :edit_password
    end
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :password, :email, :nick_name)
  end

  def user_password_params
    params.require(:user_password).permit(:password)
  end

end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  def create
    if current_user
      @vote = Vote.new(vote_params)
      @vote.share = Share.find(params["share_id"])
      @vote.user = current_user
      @vote.save
      redirect_to shares_path
    else
      @message = "You must be logged in to vote"
      render new_session_path
    end
  end

  def update
    if current_user
      @vote = Vote.find(params["id"])
      @vote.value += params[:vote][:value].to_i
      @vote.save
      redirect_to shares_path
    else
      @message = "You must be logged in to vote"
      render new_session_path
    end
  end

  def vote_params
    params.require(:vote).permit(:value)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/shares_helper.rb
module SharesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/comments/_comment_index.html.erb
<dl class="comment-block">
  <% @comments.each do |comment| %>
    <div class="row">
      <span class="comment-date-circle col-md-1 col-xs-3">
        <p class="date-month">
          <%= comment.created_at.strftime("%b") %>
        </p>
        <p class="date-day">
          <%= comment.created_at.strftime("%d") %>
        </p>
      </span>
      <div class="single-comment col-md-11 col-xs-9">
        <dt>
          <%= link_to comment.user.nick_name, user_shares_path(comment.user.id) %> <small><%= time_ago_in_words(comment.created_at) %> ago</small>
        </dt>
        <dd>
          <%= comment.body %>
        </dd>
        <dd>
          <% if comment.user == current_user %>
            <small class="share-nav"><%= link_to "Edit", edit_share_comment_path(share_id: @share.id, id: comment.id) %></small>
            <small class="share-nav"><%= link_to "Delete", share_comment_path(share_id: @share.id, id: comment.id), method: :delete %></small>
          <% end %>
        </dd>
      </div>
    </div>
  <% end %>
</dl>

app/views/comments/_single_share.html.erb
<div class=row>
  <span class="vote-section col-md-1 col-xs-2">
    <% vote = Vote.find_by(user: current_user, share_id: @share.id) %>
    <% if vote %>
      <p>
        <%= link_to "▲", vote_path(share_id: @share.id, id: vote.id, vote: { value: 1 }), method: :patch, class: "vote-up-arrow vote-#{vote.value}" %>
      </p>
      <p class="vote-total"><%= @share.net_votes %></p>
      <p>
        <%= link_to "▼", vote_path(share_id: @share.id, id: vote.id, vote: { value: -1 }), method: :patch, class: "vote-down-arrow vote-#{vote.value}" %>
      </p>
    <% else %>
      <p>
        <%= link_to "▲", share_votes_path(share_id: @share.id, vote: { value: +1 }), method: :post, class: "vote-up-arrow no-vote" %>
      </p>
      <p class="vote-total">
        <%= @share.net_votes %>
      </p>
      <p>
        <%= link_to "▼", share_votes_path(share_id: @share.id, vote: { value: -1 }), method: :post, class: "vote-down-arrow no-vote" %>
      </p>
    <% end %>
  </span>
  <span class="date-circle col-md-1 col-xs-2">
    <p class="date-month">
      <%= @share.created_at.strftime("%b") %>
    </p>
    <p class="date-day">
      <%= @share.created_at.strftime("%d") %>
    </p>
  </span>
  <article class="one-share col-md-10  col-xs-8">
    <dt>
      <h4><%= link_to @share.title, @share.url, class: "share-title" %></h4>
    </dt>
    <dd>
      <small>shared about <%= time_ago_in_words(@share.created_at) %> ago by
        <% if current_user == @share.user  %>
          you
        <% else %>
          <%= @share.user.nick_name %>
        <% end %></small>
    </dd>
    <dd>
      <% if current_user == @share.user %>
        <small class="share-nav"><%= link_to "Edit Share", edit_share_path(@share.id) %></small>
        <small class="share-nav"><%= link_to "Delete Share", share_path(@share.id), method: :delete %></small>
      <% end %>
    </dd>
  </article>
</div>

app/views/comments/edit.html.erb
<%= render 'single_share' %>
<div class="row">
  <aside class="col-md-1">
  </aside>
  <article class="col-md-11 comment-section">
    <dl class="comment-block">
      <% @share.comments.reverse.each do |comment| %>
        <% if comment == @comment %>
        <span class="comment-date-circle col-md-1  col-xs-3">
          <p class="date-month">
            <%= comment.created_at.strftime("%b") %>
          </p>
          <p class="date-day">
            <%= comment.created_at.strftime("%d") %>
          </p>
        </span>
          <div class="single-comment col-md-11 col-xs-9">
            <dt>
              <%= comment.user.nick_name %>
            </dt>
            <dd>
              <%= form_for([@share, @comment], html: { class: "form-inline" }) do |f| %>
                <div class="form-group">
                  <%= f.text_area :body, class: "form-control" %>
                </div>
                <%= f.submit "Save", class: "btn btn-primary" %>
              <% end %>
            </dd>
          </div>
        <% else %>
        <span class="comment-date-circle col-md-1 col-xs-3">
          <p class="date-month">
            <%= comment.created_at.strftime("%b") %>
          </p>
          <p class="date-day">
            <%= comment.created_at.strftime("%d") %>
          </p>
        </span>
        <div class="single-comment col-md-11 col-xs-9">
          <dt>
            <%= link_to comment.user.nick_name, user_shares_path(comment.user.id) %> <small><%= time_ago_in_words(comment.created_at) %> ago</small>
          </dt>
          <dd>
            <%= comment.body %>
          </dd>
          <dd>
            <% if comment.user == current_user %>
              <small class="share-nav"><%= link_to "Edit", edit_share_comment_path(share_id: @share.id, id: comment.id) %></small>
              <small class="share-nav"><%= link_to "Delete", share_comment_path(share_id: @share.id, id: comment.id), method: :delete %></small>
            <% end %>
          </dd>
        </div>
        <% end %>
      <% end %>
    </dl>
  </article>
</div>

app/views/comments/index.html.erb
<% if @message %>
  <div class="alert alert-danger">
    <%= @message %>
  </div>
<% end %>
<%= render 'single_share' %>
<div class="row">
  <aside class="col-md-1 col-xs-1">
  </aside>
  <article class="col-md-11 col-xs-11 comment-section">
    <small class="share-nav add-comment"><%= link_to "Add Comment", new_share_comment_path(@share.id) %></small>
    <%= render 'comment_index' %>
  </article>
</div>

app/views/comments/new.html.erb
<% @comment.errors.full_messages.each do |message| %>
  <div class="alert alert-danger">
    <% if message == "User must exist" %>
      <%= "You must be logged in to comment" %>
    <% else %>
      <%= message %>
    <% end %>
  </div>
<% end %>

<%= render 'single_share' %>
<div class="row">
  <aside class="col-md-1">
  </aside>
  <article class="col-md-11 comment-section">
    <dl class="comment-block">
      <div class="single-comment">
        <dt>
          <%= current_user.nick_name %>
        </dt>
        <dd>
          <%= form_for([@share, @comment]) do |f| %>
            <div class="form-group">
              <%= f.text_area :body, class: "form-control" %>
            </div>
            <%= f.submit "Submit", class: "btn btn-primary" %>
          <% end %>
        </dd>
      </div>
      <% @share.comments.each do |comment| %>
        <span class="comment-date-circle col-md-1 col-xs-3">
          <p class="date-month">
            <%= comment.created_at.strftime("%b") %>
          </p>
          <p class="date-day">
            <%= comment.created_at.strftime("%d") %>
          </p>
        </span>
        <div class="single-comment col-md-11 col-xs-9">
          <dt>
            <%= link_to comment.user.nick_name, user_shares_path(comment.user.id) %> <small><%= time_ago_in_words(comment.created_at) %> ago</small>
          </dt>
          <dd>
            <%= comment.body %>
          </dd>
          <dd>
            <% if comment.user == current_user %>
              <small class="share-nav"><%= link_to "Edit", edit_share_comment_path(share_id: @share.id, id: comment.id) %></small>
              <small class="share-nav"><%= link_to "Delete", share_comment_path(share_id: @share.id, id: comment.id), method: :delete %></small>
            <% end %>
          </dd>
        </div>
      <% end %>

    </dl>
  </article>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Forgeddit</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- Latest compiled and minified CSS -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </head>

  <body class="forgeddit">
    <nav class="navbar navbar-inverse">
      <div class="container-fluid">
        <a class="navbar-brand" href="/shares">Forgeddit</a>
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        <header id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Share Something", new_share_path %></li>
            <li>
              <% if current_user %>
                <%= link_to "Your Shares", user_shares_path(current_user.id) %>
              <% end %>
            </li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li>
              <% if current_user %>
                <%= link_to "Logout", session_path, method: :delete %>
              <% else %>
                <%= link_to "Login", new_session_path %>
              <% end %>
            </li>
            <li>
              <%= link_to "#{current_user.first_name} #{current_user.last_name}", user_path(current_user.id) if current_user %>
            </li>
            <li>
              <%= link_to "Sign up", new_user_path unless current_user %>
            </li>
          </ul>
        </header>
      </div>
    </nav>
    <div class="container">
      <% flash.each do |type, msg| %>
        <div class="alert alert-<%= type %>">
          <%= msg %>
        </div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/session/new.html.erb
<h1>Login</h1>
<% if @message %>
  <div class="alert alert-danger">
    <%= @message %>
  </div>
<% end %>
<%= form_tag session_path do %>
  <div class="form-group">
    <%= label_tag :email %>
    <%= email_field_tag :email, nil, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= label_tag :password %>
    <%= password_field_tag :password, nil, class:"form-control" %>
  </div>

  <%= submit_tag nil, class:"btn btn-primary" %>
<% end %>

app/views/shares/_index.html.erb
<% if @message %>
  <div class="alert alert-danger">
    <%= @message %>
  </div>
<% end %>
<dl>
  <% @shares.each do |share| %>
    <div class="row">
      <span class="vote-section col-md-1 col-xs-2">
        <% vote = Vote.find_by(user: current_user, share_id: share.id) %>
        <% if vote %>
          <p>
            <%= link_to "▲", vote_path(share_id: share.id, id: vote.id, vote: { value: 1 }), method: :patch, class: "vote-up-arrow vote-#{vote.value}" %>
          </p>
          <p class="vote-total"><%= share.net_votes %></p>
          <p>
            <%= link_to "▼", vote_path(share_id: share.id, id: vote.id, vote: { value: -1 }), method: :patch, class: "vote-down-arrow vote-#{vote.value}" %>
          </p>
        <% else %>
          <p>
            <%= link_to "▲", share_votes_path(share_id: share.id, vote: { value: +1 }), method: :post, class: "vote-up-arrow no-vote" %>
          </p>
          <p class="vote-total">
            <%= share.net_votes %>
          </p>
          <p>
            <%= link_to "▼", share_votes_path(share_id: share.id, vote: { value: -1 }), method: :post, class: "vote-down-arrow no-vote" %>
          </p>
        <% end %>
      </span>
      <span class="date-circle col-md-1 col-xs-2">
        <p class="date-month">
          <%= share.created_at.strftime("%b") %>
        </p>
        <p class="date-day">
          <%= share.created_at.strftime("%d") %>
        </p>
      </span>
      <article class="one-share col-md-10 col-xs-8">
        <dt>
          <h4><%= link_to share.title, share.url, class: "share-title" %></h4>
        </dt>
        <dd>
          <small>shared about <%= time_ago_in_words(share.created_at) %> ago by
            <% if current_user == share.user  %>
              you
            <% else %>
              <%= link_to share.user.nick_name, user_shares_path(share.user.id) %>
            <% end %></small>
        </dd>
        <dd>
          <small class="share-nav"><%= link_to "#{share.comments.size} Comments", share_comments_path(share.id) %></small>
            <% if current_user == share.user %>
              <small class="share-nav"><%= link_to "Edit Share", edit_share_path(share.id) %></small>
              <small class="share-nav"><%= link_to "Delete Share", share_path(share.id), method: :delete %></small>
            <% end %>
        </dd>
      </article>
    </div>
  <% end %>
</dl>

app/views/shares/edit.html.erb
<h1>Edit Share</h1>
<% @share.errors.full_messages.each do |message| %>
    <div class="alert alert-danger"><%= message %></div>
<% end %>
<%= form_for @share do |f| %>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :url %>
    <%= f.url_field :url, class: "form-control" %>
  </div>

  <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/shares/index.html.erb
<%= render 'index' %>

app/views/shares/new.html.erb
<h1>Share Something</h1>

  <% @share.errors.full_messages.each do |message| %>
      <div class="alert alert-danger"><%= message %></div>
  <% end %>

<%= form_for @share do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :url %>
    <%= f.url_field :url, class:"form-control" %>
  </div>

  <%= f.submit class:"btn btn-primary" %>
<% end %>

app/views/shares/user_shares.html.erb
<% if current_user == @user  %>
  <h1>Your Shares</h1>
<% else %>
  <h1><%= @user.nick_name %>'s Shares</h1>
<% end %>
<%= render 'index' %>

app/views/users/edit.html.erb
<h1>Edit your profile</h1>

<% @user.errors.full_messages.each do |message| %>
    <div class="alert alert-danger"><%= message %></div>
<% end %>

<%= form_for @user do |f| %>
  <div class="form-group">
    <%= f.label :email %>
    <%= f.email_field :email, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :first_name %>
    <%= f.text_field :first_name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :last_name %>
    <%= f.text_field :last_name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :nick_name %>
    <%= f.text_field :nick_name, class: "form-control" %>
  </div>

  <%= f.submit class: "btn btn-primary" %>

<% end %>

app/views/users/edit_password.html.erb
<h1>Change your password</h1>

<% if @message %>
  <div class="alert alert-danger"><%= @message %></div>
<% end %>
<% @user.errors.full_messages.each do |message| %>
    <div class="alert alert-danger"><%= message %></div>
<% end %>

<%= form_tag user_update_password_path(@user.id), method: :patch do %>
  <%= label_tag "user_password[password]", "New Password" %>
  <%= password_field_tag "user_password[password]" %>

  <%= label_tag "user_password[confirm_password]", "Confirm Password" %>
  <%= password_field_tag "user_password[confirm_password]" %>

  <%= submit_tag "Save", class: "btn btn-primary"%>
<% end %>

app/views/users/new.html.erb
<h1>Create a login</h1>

<% @user.errors.full_messages.each do |message| %>
    <div class="alert alert-danger"><%= message %></div>
<% end %>
<% if @message %>
  <div class="alert alert-danger"><%= @message %></div>
<% end %>

<%= form_for @user do |f| %>
  <div class="form-group">
    <%= f.label :email %>
    <%= f.text_field :email, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :first_name %>
    <%= f.text_field :first_name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :last_name %>
    <%= f.text_field :last_name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :nick_name %>
    <%= f.text_field :nick_name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :password %>
    <%= f.password_field :password, class: "form-control" %>
  </div>

  <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/users/show.html.erb
<h1><%= "#{current_user.first_name} #{current_user.last_name}" %></h1>
<h5>Forgeddit member for <%= time_ago_in_words(current_user.created_at) %></h5>
<dl class="dl-horizontal">
  <dt>
    Email
  </dt>
  <dd>
    <%= current_user.email %>
  </dd>
  <dt>
    First Name
  </dt>
  <dd>
    <%= current_user.first_name %>
  </dd>
  <dt>
    Last Name
  </dt>
  <dd>
    <%= current_user.last_name %>
  </dd>
  <dt>
    Nickname
  </dt>
  <dd>
    <%= current_user.nick_name %>
  </dd>
</dl>
<small class="profile-nav"><%= link_to "Edit Profile Info", edit_user_path(current_user.id) %></small>
<small class="profile-nav"><%= link_to "Change Password", user_edit_password_path(current_user.id) %></small>

app/views/votes/edit.html.erb
<h1>Votes#edit</h1>
<p>Find me in app/views/votes/edit.html.erb</p>

app/views/votes/show.html.erb
<h1>Votes#show</h1>
<p>Find me in app/views/votes/show.html.erb</p>